# Generated by Django 4.2 on 2025-05-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_options_remove_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
